### ISSUE TITLE
Cannot take screenshot

### ISSUE THREAD

**Issue by minhui27** [MOLPay/molpay-mobile-xdk-cordova#1]
After installed this plugin, the app cannot take screenshot due to limited storage space, or it isn't allowed by the app or your organisation.

**Comment by clewlb** [comment]
@minhui27,

Due to payment security concerns, our plugins applied the secured_flag on Android platform whenever the XDK is initiated and released it after XDK is dismissed after the payment is done. However due to the nature of Android platform, it is known that only Android 6 (Marshmallow) allows runtime remover of the secured_flag, all Android versions below 6 will be locked with the secured_flag on app runs.

If you have a concern that your app must requires that secured_flag be removed permanently, please write to our support and request a custom XDK which comes with secured_flag removed, however, if you choose to receive a custom XDK, you will not be able to receive out latest updates through our public Github repo.

Thanks.

MOLPay Mobile Team
